# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Page2 import Ui_Form
from Page3 import Ui_Form1
import nltk
nltk.download('stopwords')
# Ui file
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 731)
        MainWindow.setStyleSheet("background-color:rgb(132, 132, 132)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Widget1 = QtWidgets.QWidget(self.centralwidget)
        self.Widget1.setGeometry(QtCore.QRect(290, 20, 501, 621))
        self.Widget1.setStyleSheet("background-color:rgb(230, 230, 230)")
        self.Widget1.setObjectName("Widget1")
        self.Label1 = QtWidgets.QLabel(self.Widget1)
        self.Label1.setGeometry(QtCore.QRect(100, 20, 301, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Label1.setFont(font)
        self.Label1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label1.setObjectName("Label1")
        self.UsernameInput = QtWidgets.QLineEdit(self.Widget1)
        self.UsernameInput.setGeometry(QtCore.QRect(70, 170, 341, 71))
        self.UsernameInput.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(105, 118, 132);\n"
"padding-bottom:7px;\n"
"")
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(self.Widget1)
        self.PasswordInput.setGeometry(QtCore.QRect(70, 320, 341, 71))
        self.PasswordInput.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(105, 118, 132);\n"
"padding-bottom:7px;\n"
"")
        self.PasswordInput.setObjectName("PasswordInput")
        self.loginButton = QtWidgets.QPushButton(self.Widget1)
        self.loginButton.setGeometry(QtCore.QRect(170, 460, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loginButton.clicked.connect(self.Page2)

    # Function for the program to connect to Page2
    def Page2(self):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
        MainWindow.close()
    
    # Ui function
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label1.setText(_translate("MainWindow", "Log in"))
        self.UsernameInput.setPlaceholderText(_translate("MainWindow", "Username: "))
        self.PasswordInput.setPlaceholderText(_translate("MainWindow", "Password: "))
        self.loginButton.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":

    nltk.download('stopwords')
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
